### PR TITLE
disable trimming by default

### LINKED ISSUE #94: Disable trimming *and* wrapping?
Hi folks,

I'm a new user to node-foreman, but really excited by it. Thanks for all the great work!

Like others, I ran into the discovery that logs get trimmed (truncated) by default. Feedback: that feels like a particularly unfriendly default to me.

I studied the code and discovered `--wrap` (as noted in issue #88), but I ran into issue #89 where this doesn't seem to actually work for me.

I thought okay, I'll just set the trim to be really high (e.g. `--trim 99999999`). But it turns out even then, the code wraps to 500 chars by default — with no way to override this:

https://github.com/strongloop/node-foreman/blob/52e940117f569ebafcddc8d2a1fd41c1148dbbc0/lib/console.js#L40

https://github.com/strongloop/node-foreman/blob/52e940117f569ebafcddc8d2a1fd41c1148dbbc0/nf.js#L84-L93

A 500-char wrap might sound reasonable, but wrapping in general is often undesirable to me:

```
11:19:41 AM api.1 |  ... meta={"reqType":"priv
11:19:41 AM api.1 |  >  ate"} that was hard to read
11:19:41 AM api.1 |  ... https://some_lo
11:19:41 AM api.1 |  >  ng_url that I used to be able to cmd+double-click
```

As noted in issue https://github.com/strongloop/node-foreman/issues/33#issuecomment-74117284, wrapping feels unnecessary since the terminal already wraps natively (without breaking the log apart).

So I'd love a way to disable _both_ trimming and wrapping. Thank you!

### PR DESCRIPTION
**Pull request by dickeyxxx**
fixes #94
fixes #98
fixes https://github.com/heroku/heroku-local/issues/17

notably for me this doesn't work anyways: 
screen shot 2016-04-05 at 6 05 11 pm

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by rmg** [comment]
@slnode ok to test

**Comment by rmg** [comment]
@dickeyxxx I've merged #106 (and a few other minor changes), so this will need to be rebased.

**Comment by dickeyxxx** [comment]
thanks! updated all my branches

**Pull request merged**
