### PR TITLE
Changed handler name to error instead of proxyError

### PR DESCRIPTION
**Pull request by nazarhussain**
As per documented for http-proxy https://www.npmjs.com/package/http-proxy#listening-for-proxy-events

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by nazarhussain** [comment]
Any admin there to review and merge this PR.

**Comment by rmg** [comment]
@slnode ok to test

**Comment by nazarhussain** [comment]
Anyone can look into and suggest why the test failed on `windows` and `mac`?

**Comment by dickeyxxx** [comment]
@nazarhussain https://github.com/strongloop/node-foreman/pull/106

**Pull request closed without merging**
