### PR TITLE
Dont' drop sudo

### PR DESCRIPTION
**Pull request by vyorkin**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by vyorkin** [comment]
fixes #70, replaces #71

**Comment by rmg** [comment]
@slnode ok to test

**Comment by rmg** [comment]
@vyorkin have you signed the CLA? https://cla.strongloop.com/agreements/strongloop/node-foreman

**Comment by vyorkin** [comment]
@rmg yes, just now

**Pull request merged**
