### PR TITLE
Add '' argument to sed -i to fix mac os tests

### PR DESCRIPTION
**Pull request by ransombriggs**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by dickeyxxx** [comment]
I rebased https://github.com/strongloop/node-foreman/pull/106 off of this to see how the test suite looks

**Comment by rmg** [comment]
@slnode ok to test

**Comment by rmg** [comment]
The failures on CI are unrelated and it passes for me locally, so I'm going to land this as is.

**Pull request merged**
