### PR TITLE
Cleanup: No need to duplicate the color keys, can use Object.keys() to extract from colors object

### PR DESCRIPTION
**Pull request by bboysathish**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by rmg** [comment]
@slnode ok to test

**Comment by rmg** [comment]
@bboysathish thanks for the cleanup :-)

**Comment by rmg** [comment]
@bboysathish for future reference, please keep the first line of the commit message to 50 chars or less :-)

**Pull request merged**
