### PR TITLE
Add ability to output raw console statements. Resolves #33

### LINKED ISSUE #33: output bare console logs
Would it be possible the provide an option that would avoid appending timestamps and wrapping log lines?

### PR DESCRIPTION
**Pull request by foiseworth**
Please let me know if this requires any further work

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by rmg** [comment]
@slnode ok to test

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by foiseworth** [comment]
@rmg many thanks for looking at this. Looking are the test failures, do they normally pass? I'm struggling to see why this change would cause the failures.

**Pull request closed without merging**
