### PR TITLE
Lint and test on Node.js 0.12.x and io.js 1.6.x

### PR DESCRIPTION
**Pull request by e-jigsaw**
Hi,

This PR contains two features.

* Add jshint
* Add test for Node.js 0.12.x and io.js 1.6.x in travis

I wanted to add new `restart` feature. But, to read a code is hard for me. So I add jshint in first. Then I was refactoring a code based on the jshint's warning and error. After that, I noticed Node.js 0.12.x and io.js do not tested in travis when I tested a codes. So I edited `.travis.yml`.

Thanks

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by seriousben** [comment]
I think it would be easier to merge for maintainer if the linting was not done in the same PR.

**Comment by rmg** [comment]
@slnode ok to test

**Comment by rmg** [comment]
@e-jigsaw that's a lot of work cleaning up this mess, thanks for all your effort. It's still not quite the preferred style, but it's consistent and infinitely better than the mishmash that was there :+1: 

@seriousben in this case all that was meant by "adding support" was adding them to the travis config, so it's pretty minor.

**Comment by e-jigsaw** [comment]
@rmg thanks :+1:

**Pull request merged**
