### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by leebradley**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by leebradley** [comment]
CLA failing because I accepted the CLA after making the pull request. Tried closing and opening the pull request, but the CI didn't retrigger.

**Comment by bajtos** [comment]
Landed, thank you for the contribution!

**Pull request merged**
