### PR TITLE
Add a -d / --indent option to preserve indentation in the output.

### PR DESCRIPTION
**Pull request by jeffreywescott**
Defaults to false to preserve backward compatibility.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by growlsworth** [comment]
I feel like preserving indentation should be the default behavior. Thanks for the PR @jeffreywescott.

**Comment by rmg** [comment]
@slnode ok to test

**Comment by rmg** [comment]
I'm inclined to agree with @growlsworth. The indentation should probably be preserved and the `--trim` and `--wrap` options should be used if people find their indented logs are being trimmed too aggressively.

**Comment by rmg** [comment]
@jeffreywescott I noticed the whitespace inconsistencies in your patch and decided to just fix the whitespace in that file on master. Unfortunately that introduces a merge conflict for this PR.

Rather than just fixing the whitespace, what do you think about just removing the call to String#trim entirely and submitting that as a PR?

**Comment by jeffreywescott** [comment]
I'm happy to submit a new PR. The only reason I added the option was to maintain backward-compatibility (in case the authors wanted it). I can do that later today if necessary. But honestly, if that's the plan, why don't you just _do_ that on master and skip the PR process? I certainly don't care about "credit" for the patch. :-P

**Comment by rmg** [comment]
@jeffreywescott some people like to get credit. I'll go ahead and do it myself :-)

**Comment by rmg** [comment]
Released as v1.3.0.

**Pull request closed without merging**
