### PR TITLE
Dropping root privileges moved to a separate package

### PR DESCRIPTION
**Pull request by PavelVanecek**
while proxy.js implemented this functionality properly, there were some problems with they way it was implemented in forward.js and nf.js.
This fixes https://github.com/strongloop/node-foreman/issues/70

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by rmg** [comment]
ok to test

**Comment by rmg** [comment]
@PavelVanecek I was thinking removing all those places where privilege dropping is done and only doing it on lib/proc.js:25 and lib/proc.js:70 (just before the spawn calls). This eliminates the problem where listening doesn't finish until after the child process has been started and the app still ends up running as root.

**Comment by PavelVanecek** [comment]
@rmg what if the lib/proc.js:24 dropsudo() call is executed before the .listen finished? Will that not throw a insufficient privilege error?

**Comment by rmg** [comment]
@PavelVanecek it's a race condition either way.. the alternative is to not drop privileges at all.. which I'm actually ok with, since this is a dev-time tool anyway.

**Pull request closed without merging**
