### PR TITLE
multiple proxies and forward proxy bugfixes

### PR DESCRIPTION
**Pull request by barbuza**
`forward.js` updated to match `http-proxy` api from it's docs

loop issue fixed in `proxy.js`

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by rmg** [comment]
ok to test

**Comment by rmg** [comment]
@barbuza it looks like this also adds support for websockets as a side effect, is that accurate?

**Comment by barbuza** [comment]
@rmg in my case they didn't work as expected (tried with socket.io), added them just to follow reference docs

**Pull request merged**
