### PR TITLE
Add multiline support to key=value env config

### PR DESCRIPTION
**Pull request by dytsai**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by rmg** [comment]
@slnode ok to test

**Comment by dytsai** [comment]
Anything I can do to help merge this pull request? I saw it succeeded the checks except appveyor build but I am not sure what's wrong.

**Comment by bajtos** [comment]
Hello @dytsai, are you still keen to get this landed? In general, we are reluctant to make changes without a test coverage. Is there any reasonably-easy way how to write a test that fails on the current master and passes with your changes in place?

**Comment by nmccready** [comment]
Why did this slip through the cracks?

**Pull request closed without merging**
