### PR TITLE
fix exit/kill events

### PR DESCRIPTION
**Pull request by RasPhilCo**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by vvo** [comment]
Hey hi @RasPhilCo is this similar to https://github.com/algolia/node-foreman/commit/14e2c7cf265ca6d8daa42b32f2e27a2dc8f272ba and https://github.com/algolia/node-foreman/commit/c5119546053138c109e66e57fd2b388e7da7fb77?

cc @Jerskouille

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by RasPhilCo** [comment]
Haven't tested, but looks similar. Not sure why the commit history is now wonky though.

**Comment by bajtos** [comment]
Some of the exit behavior has been fixed by https://github.com/strongloop/node-foreman/pull/155/commits/bcd3b2333cee2b5db2a34f1894a7c811a621c1f5. If there are any remaining problems, then please open a new PR please.

**Pull request closed without merging**
