### PR TITLE
SupervisorCtl to use group name instead of application name as groupname

### PR DESCRIPTION
**Pull request by arvindkumarc**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by arvindkumarc** [comment]
The Appveyor build for node-0.12 has to be retriggered.

**Comment by arvindkumarc** [comment]
Are there any admins to validate to accept/reject the provided patch?

**Pull request closed without merging**
